<a href="https://colab.research.google.com/github/fsndzomga/Deep-Learning-With-Python/blob/main/Predictive_modeling_for_time_series_data_using_recurrent_neural_networks_(RNNs)_and_long_short_term_memory_(LSTM)_networks_with_TensorFlow_and%C2%A0Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def prepare_data(data, timesteps):
  X = []
  y = []
  for i in range(timesteps, len(data)):
    X.append(data[i-timesteps:i])
    y.append(data[i])
  X, y = np.array(X), np.array(y)
  return X, y

In [10]:
import numpy as np

def generate_primes(n):
    primes = []
    num = 2
    while len(primes) < n:
        is_prime = True
        for p in primes:
            if num % p == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
        num += 1
    return np.array(primes)


In [11]:
data = generate_primes(1000)
timesteps = 3
X, y = prepare_data(data, timesteps)
print(X)
print(y)

[[   2    3    5]
 [   3    5    7]
 [   5    7   11]
 ...
 [7877 7879 7883]
 [7879 7883 7901]
 [7883 7901 7907]]
[   7   11   13   17   19   23   29   31   37   41   43   47   53   59
   61   67   71   73   79   83   89   97  101  103  107  109  113  127
  131  137  139  149  151  157  163  167  173  179  181  191  193  197
  199  211  223  227  229  233  239  241  251  257  263  269  271  277
  281  283  293  307  311  313  317  331  337  347  349  353  359  367
  373  379  383  389  397  401  409  419  421  431  433  439  443  449
  457  461  463  467  479  487  491  499  503  509  521  523  541  547
  557  563  569  571  577  587  593  599  601  607  613  617  619  631
  641  643  647  653  659  661  673  677  683  691  701  709  719  727
  733  739  743  751  757  761  769  773  787  797  809  811  821  823
  827  829  839  853  857  859  863  877  881  883  887  907  911  919
  929  937  941  947  953  967  971  977  983  991  997 1009 1013 1019
 1021 1031 1033 1039 1049 1051 106

In [9]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split

# generate example data
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
timesteps = 3
X, y = prepare_data(data, timesteps)

# split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


# create and compile the model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(timesteps, 1)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse', metrics='accuracy')

# fit the model to the training data
model.fit(X_train, y_train, epochs=100, validation_split=0.2)

# evaluate the model on the testing data
loss = model.evaluate(X_test, y_test)
print('Test loss:', loss)

Epoch 1/100
1/1 [==============================] - 4s 4s/step - loss: 41.6525 - val_loss: 34.9329
Epoch 2/100
1/1 [==============================] - 0s 72ms/step - loss: 41.3423 - val_loss: 34.6967
Epoch 3/100
1/1 [==============================] - 0s 79ms/step - loss: 41.0283 - val_loss: 34.4606
Epoch 4/100
1/1 [==============================] - 0s 68ms/step - loss: 40.7088 - val_loss: 34.2206
Epoch 5/100
1/1 [==============================] - 0s 73ms/step - loss: 40.3790 - val_loss: 33.9747
Epoch 6/100
1/1 [==============================] - 0s 99ms/step - loss: 40.0383 - val_loss: 33.7252
Epoch 7/100
1/1 [==============================] - 0s 91ms/step - loss: 39.6850 - val_loss: 33.4645
Epoch 8/100
1/1 [==============================] - 0s 104ms/step - loss: 39.3159 - val_loss: 33.1922
Epoch 9/100
1/1 [==============================] - 0s 62ms/step - loss: 38.9243 - val_loss: 32.9068
Epoch 10/100
1/1 [==============================] - 0s 64ms/step - loss: 38.5084 - val_loss: 32.6017
